### PR TITLE
Android X

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by jballoffet** [comment]
Thanks for your pull request. We are unable to fully migrate yet to AndroidX due to internal reasons. We’ll proceed when possible.

**Comment by jballoffet** [comment]
We have started internal review. Please don’t push any more changes into this PR as they might be overwritten.

**Comment by jballoffet** [comment]
Your proposed changes have been internally merged and they will be included in the next release. Thanks for contributing to Cardboard!

**Comment by xinyunh0929** [comment]
This was merged in v1.6.0.

**Pull request closed without merging**
