### PR TITLE
Fixed crash on start after stop

### PR DESCRIPTION
**Pull request by dletozeun**
Hello,

FYI, here is the quick fix done to solve the crash mentioned in #98.
It works at least but not sure it is correct memory wise.

### CODE REVIEW

**Comment by JoaoBorks** [comment]
@dletozeun can you tell if your PR fixes #117 ?

**Comment by dletozeun** [comment]
> @dletozeun can you tell if your PR fixes #117 ?

I have replied you on your issue, it should help partially.

**Comment by JoaoBorks** [comment]
@dletozeun I have tested your PR changes and they **indeed fix the crashes**. I was experiencing a distorted screen after exiting VR, as if it were rendering the left eye, but it was successfully handled with a [`camera.ResetAspect()`](https://docs.unity3d.com/ScriptReference/Camera.ResetAspect.html) after deinitializing the cardboard. Please proceed with the PR by signing the google cla and requesting review!

**Review by JoaoBorks — APPROVED** [review]

**Comment by dletozeun** [comment]
@googlebot I signed it!

**Review by Dankann — APPROVED** [review]

**Comment by agalbachicar-gg** [comment]
Sorry for the late reply. This was solved in Cardboard SDK v1.3.0 so it will no longer be needed. Anyways, thanks a lot for your contribution.

**Pull request closed without merging**
