### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by hannesa2**
Please see commit messages

### CODE REVIEW

**Comment by jballoffet** [comment]
Thanks @hannesa2 for your pull request! Changes LGTM. We'll proceed with merging these changes as soon as we're able to do it internally. Thanks!

**Comment by hannesa2** [comment]
@jballoffet There are still issues remainig

**Comment by arilow** [comment]
Many changes from this PR have already been internally merged and will be part of release v1.12.0.  
Given that some of the changes are going to be added in a future release, we are keeping this PR open.

Thanks for your contribution to Cardboard!

**Comment by jballoffet** [comment]
Most of the changes proposed here have been internally merged and they will be included in the next release. Once the new release is out, feel free to create a new PR proposing the remaining changes (we haven't been able to merge them yet due to internal reasons). Thanks for contributing to Cardboard!

**Comment by xinyunh0929** [comment]
Merged in 1.13.0

**Pull request closed without merging**
