### PR TITLE
Simplify code

### PR DESCRIPTION
**Pull request by hannesa2**
It simplify by remove unneeded constants

### CODE REVIEW

**Comment by hannesa2** [comment]
I see it needs first https://github.com/googlevr/cardboard/pull/273

**Comment by arilow** [comment]
Thanks @hannesa2 for your pull request! Changes LGTM. We'll proceed with merging these changes as soon as we're able to do it internally.

**Comment by jballoffet** [comment]
Your proposed changes have been already internally merged and will be included in the next release. Thanks for contributing to Cardboard!

**Comment by xinyunh0929** [comment]
This was merged in 1.14.0

**Pull request closed without merging**
